# NOTE: This dockerfile relies on precompiled binaries already existing on the host at
# target/<docker-target>/metallb-dyn6.
# Example: target/linux/amd64/metallb-dyn6
FROM debian:bookworm-slim
ARG TARGETPLATFORM

COPY target/${TARGETPLATFORM}/metallb-dyn6 /usr/local/bin/
RUN chmod +x /usr/local/bin/metallb-dyn6

# run unprivileged
USER 1001

CMD ["metallb-dyn6"]
